version: '3'

services:
  frontend:
    # mem_limit: 4g
    # memswap_limit: 6g
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    build:
      context: .
    ports:
      - '${NGINX_PORT}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096
      - NPM_CONFIG_REGISTRY=https://registry.npmjs.org/
